# PackaTrack Gradle configuration
org.gradle.jvmargs=-Xmx3072m -Dfile.encoding=UTF-8 -XX:+UseParallelGC
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.parallel=true

# AndroidX
android.useAndroidX=true
android.nonTransitiveRClass=true

# Kotlin code style
kotlin.code.style=official

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true
